#ifndef __CGLA_CGLA_H__
#define __CGLA_CGLA_H__

#include "BitMask.h"
#include "CGLA-util.h"
#include "ExceptionStandard.h"
#include "Mat2x2d.h"
#include "Mat2x2f.h"
#include "Mat2x3d.h"
#include "Mat2x3f.h"
#include "Mat3x3d.h"
#include "Mat3x3f.h"
#include "Mat4x4d.h"
#include "Mat4x4f.h"
#include "Quatd.h"
#include "Quaternion.h"
#include "Quatf.h"
#include "TableTrigonometry.h"
#include "UnitVector.h"
#include "Vec2d.h"
#include "Vec2f.h"
#include "Vec2i.h"
#include "Vec2ui.h"
#include "Vec3d.h"
#include "Vec3f.h"
#include "Vec3i.h"
#include "Vec3uc.h"
#include "Vec3usi.h"
#include "Vec4d.h"
#include "Vec4f.h"
#include "Vec4i.h"
#include "Vec4uc.h"
#include "eigensolution.h"
#include "statistics.h"
#include "ls_solve.h"

#endif
